// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMlmpWwzqnqgPGNoKX2nEHH__-CMHc9Os',
    appId: '1:235373640811:web:3fb8e6e2f8a295b9c9052e',
    messagingSenderId: '235373640811',
    projectId: 'studify-project-app',
    authDomain: 'studify-project-app.firebaseapp.com',
    storageBucket: 'studify-project-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoCVnv-RPD8g3YYjBvzcX0HJU_NnHooXg',
    appId: '1:235373640811:android:c750aa26be302099c9052e',
    messagingSenderId: '235373640811',
    projectId: 'studify-project-app',
    storageBucket: 'studify-project-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1bVQGQF81lw82qcD0EA71FdGOl3uuWqI',
    appId: '1:235373640811:ios:53c7328eade87f45c9052e',
    messagingSenderId: '235373640811',
    projectId: 'studify-project-app',
    storageBucket: 'studify-project-app.firebasestorage.app',
    iosBundleId: 'com.example.studifyProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1bVQGQF81lw82qcD0EA71FdGOl3uuWqI',
    appId: '1:235373640811:ios:53c7328eade87f45c9052e',
    messagingSenderId: '235373640811',
    projectId: 'studify-project-app',
    storageBucket: 'studify-project-app.firebasestorage.app',
    iosBundleId: 'com.example.studifyProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMlmpWwzqnqgPGNoKX2nEHH__-CMHc9Os',
    appId: '1:235373640811:web:c120f7f2c94b9de3c9052e',
    messagingSenderId: '235373640811',
    projectId: 'studify-project-app',
    authDomain: 'studify-project-app.firebaseapp.com',
    storageBucket: 'studify-project-app.firebasestorage.app',
  );
}
